name: Release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build Binaries
        run: |
          GOOS=darwin GOARCH=amd64 go build -ldflags="-X main.version=${{ env.VERSION }}" -o wisshrd-darwin-amd64
          GOOS=darwin GOARCH=arm64 go build -ldflags="-X main.version=${{ env.VERSION }}" -o wisshrd-darwin-arm64
          GOOS=linux GOARCH=amd64 go build -ldflags="-X main.version=${{ env.VERSION }}" -o wisshrd-linux-amd64
          GOOS=linux GOARCH=arm64 go build -ldflags="-X main.version=${{ env.VERSION }}" -o wisshrd-linux-arm64
          chmod +x wisshrd-*

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            wisshrd-darwin-amd64
            wisshrd-darwin-arm64
            wisshrd-linux-amd64
            wisshrd-linux-arm64
          draft: false
          prerelease: false
          generate_release_notes: true